---
title: "K means cluster"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Example of shiny app for k means clustering

### How to use ?

Select the parameters below and the plot would be upadate automatically

```{r, echo=FALSE}
shinyApp(
  

  
  ui = function() {
    vars <- setdiff(names(iris), "Species")
    pageWithSidebar(
      headerPanel('Iris k-means clustering'),
      sidebarPanel(
        selectInput('xcol', 'X Variable', vars),
        selectInput('ycol', 'Y Variable', vars, selected = vars[[2]]),
        numericInput('clusters', 'Cluster count', 3, min = 1, max = 9),
      ),
      mainPanel(
        plotOutput('plot1')
      )
    )
  },


  server = function(input, output, session) {
    
    # Combine the selected variables into a new data frame
    selectedData <- reactive({
      iris[, c(input$xcol, input$ycol)]
    })
    
    clusters <- reactive({
      kmeans(selectedData(), input$clusters)
    })
    
    output$plot1 <- renderPlot({
      palette(c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3",
                "#FF7F00", "#FFFF33", "#A65628", "#F781BF", "#999999"))
      
      par(mar = c(5.1, 4.1, 0, 1))
      plot(selectedData(),
           col = clusters()$cluster,
           pch = 20, cex = 3)
      points(clusters()$centers, pch = 4, cex = 4, lwd = 4)
    })
    
  },

  options = list(height = 500)
)
```