---
title: "Week 4 assignment"
author: Dion Aditya
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: slidy_presentation
runtime: shiny
---

# Background

The shiny apps is to demo k means clustering for shiny app. 

<blockquote>
k-means clustering is a method of vector quantization, originally from signal processing, that aims to partition n observations into k clusters in which each observation belongs to the cluster with the nearest mean (cluster centers or cluster centroid), serving as a prototype of the cluster. This results in a partitioning of the data space into Voronoi cells. k-means clustering minimizes within-cluster variances (squared Euclidean distances), but not regular Euclidean distances, which would be the more difficult Weber problem: the mean optimizes squared errors, whereas only the geometric median minimizes Euclidean distances. For instance, better Euclidean solutions can be found using k-medians and k-medoids
</blockquote>

# Demo

```{r,echo=FALSE, message=FALSE, warning=FALSE,comment=FALSE,error=FALSE}
shinyApp(
  ui = function() {
    vars <- setdiff(names(iris), "Species")
    pageWithSidebar(
      headerPanel('Iris k-means clustering'),
      sidebarPanel(
        selectInput('xcol', 'X Variable', vars),
        selectInput('ycol', 'Y Variable', vars, selected = vars[[2]]),
        numericInput('clusters', 'Cluster count', 3, min = 1, max = 9),
      ),
      mainPanel(
        plotOutput('plot1')
      )
    )
  },


  server = function(input, output, session) {
    
    # Combine the selected variables into a new data frame
    selectedData <- reactive({
      iris[, c(input$xcol, input$ycol)]
    })
    
    clusters <- reactive({
      kmeans(selectedData(), input$clusters)
    })
    
    output$plot1 <- renderPlot({
      palette(c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3",
                "#FF7F00", "#FFFF33", "#A65628", "#F781BF", "#999999"))
      
      par(mar = c(5.1, 4.1, 0, 1))
      plot(selectedData(),
           col = clusters()$cluster,
           pch = 20, cex = 3)
      points(clusters()$centers, pch = 4, cex = 4, lwd = 4)
    })
    
  },

  options = list(height = 500)
)
```

# Documentation

You can see the shiny app here:
https://dionaditya.shinyapps.io/doc1/

The code repo:
https://github.com/dionaditya/submission_week4


# References

- https://en.wikipedia.org/wiki/K-means_clustering

